export const FORM_DATA_LOAD_TO_REDUX = 'FORM_DATA_LOAD_TO_REDUX';
export const FORM_DATA_CLEAR_TO_REDUX = 'FORM_DATA_CLEAR_TO_REDUX';
export const FORM_DATA_REMOVE_TO_REDUX = 'FORM_DATA_REMOVE_TO_REDUX';
